server:
  context-path: /MusicManage
  port: 8865
spring:
  http:
    encoding:
      charset: utf-8
      enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    druid:
      maxActive: 100
      initialSize: 1
      minIdle: 1
      maxWait: 60000
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
      validationQuery: SELECT 'x' from dual
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 900000
      filters: config,stat,wall,slf4j
      filter.stat.db-type: mysql
      filter.stat.merge-sql: true
      filter.stat.slow-sql-millis: 1000
      filter.stat.log-slow-sql: true
      filter.log4j.connection-log-enabled: true
mybatis:
  type-aliases-package: com.musicManage.dao.model
  mapper-locations: classpath*:mybatis/*.xml  
redis:
    host: 127.0.0.1
    port: 6379
    password: null
    timeout: 3000
    pool:
      max-active: 50
      max-idle: 10
      max-wait: 5 
#
QQ_Origin: QQmusic
QQ_UserPlaylistId: 576140241
QQ_UserPlaylistcid: 205360838
#
Net_Origin: NetEasemusic
Net_UserPlaylistId: 77096164


downloadFileDir: E:/music_manage